# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - '.gitignore'
      - '.jujuignore'
      - 'LICENSE'
      - '**.md'
      - .github/renovate.json5
      - '.github/workflows/sync_docs.yaml'
  schedule:
    - cron: '53 0 * * *'  # Daily at 00:53 UTC
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:

jobs:
  lint-workflows:
    name: Lint .github/workflows/
    uses: canonical/data-platform-workflows/.github/workflows/lint_workflows.yaml@v49.0.2
    permissions:
      contents: read

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install tox & uv
        run: |
          pipx install tox
          sudo snap install astral-uv --classic
      - name: tox run -e lint
        run: tox run -e lint
    permissions: {}

  unit-test:
    name: Unit test charm
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install tox & uv
        run: |
          pipx install tox
          sudo snap install astral-uv --classic
      - name: Run tests
        run: tox run -e unit
    permissions: {}
