# This file based on https://samber.github.io/awesome-prometheus-alerts/rules#pgbouncer-1

groups:

- name: PgbouncerExporterK8s

  rules:

    # 2.5.1
    - alert: PgbouncerActiveConnections
      expr: 'pgbouncer_pools_server_active_connections > 200'
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: PgBouncer instance {{ $labels.instance }} has > 200 active connections
        description: |
          Consider checking the client application responsible for generating those additional connections.
          LABELS = {{ $labels }}

    # 2.5.2
    # 10 -> 3
    - alert: PgbouncerErrors
      expr: 'increase(pgbouncer_errors_count{errmsg!="server conn crashed?"}[1m]) > 3'
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: PgBouncer instance {{ $labels.instance }} is logging errors. 
        description: |
          This may be due to a a server restart or an admin typing commands at the PgBouncer console.
          VALUE = {{ $value }}
          LABELS = {{ $labels }}

    # 2.5.3
    - alert: PgbouncerMaxConnections
      expr: 'increase(pgbouncer_errors_count{errmsg="no more connections allowed (max_client_conn)"}[30s]) > 0'
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: PgBouncer instance {{ $labels.instance }} has reached `max_client_conn`.
        description: |
          Consider checking how many connections the client application is opening.
          VALUE = {{ $value }}
          LABELS = {{ $labels }}
