# This file based on https://samber.github.io/awesome-prometheus-alerts/rules#pgbouncer-1

groups:

- name: PgbouncerExporterK8s

  rules:

    # 2.5.1
    - alert: PgbouncerActiveConnections
      expr: 'pgbouncer_pools_server_active_connections > 200'
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: PgBouncer active connections (instance {{ $labels.instance }})
        description: |
        `PgBouncer pools are filling up.
        VALUE = {{ $value }}
        LABELS = {{ $labels }}`

    # 2.5.2
    # 10 -> 3
    - alert: PgbouncerErrors
      expr: 'increase(pgbouncer_errors_count{errmsg!="server conn crashed?"}[1m]) > 3'
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: PgBouncer errors (instance {{ $labels.instance }})
        description: |
        `PgBouncer is logging errors.
        This may be due to a a server restart or an admin typing commands at the PgBouncer console.
        VALUE = {{ $value }}
        LABELS = {{ $labels }}`

    # 2.5.3
    - alert: PgbouncerMaxConnections
      expr: 'increase(pgbouncer_errors_count{errmsg="no more connections allowed (max_client_conn)"}[30s]) > 0'
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: PgBouncer max connections (instance {{ $labels.instance }})
        description: |
        The number of PgBouncer client connections has reached `max_client_conn`.
        Consider double-checking how many connections the client application is opening.
        VALUE = {{ $value }}
        LABELS = {{ $labels }}`
