kind: Service
apiVersion: v1
metadata:
  labels:
    role: master
  name: {{ app_name }}-primary
spec:
  ports:
    - name: database
      port: 5432
      targetPort: 5432
    - name: api
      port: 8008
      targetPort: 8008
  selector:
    cluster-name: patroni-{{ app_name }}
    role: master

---
kind: Service
apiVersion: v1
metadata:
  labels:
    role: replica
  name: {{ app_name }}-replicas
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    cluster-name: patroni-{{ app_name }}
    role: replica
