kind: Service
apiVersion: v1
metadata:
  labels:
    role: master
  name: {{ app_name }}-primary
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    cluster-name: patroni-{{ app_name }}
    role: master

---
kind: Service
apiVersion: v1
metadata:
  labels:
    role: replica
  name: {{ app_name }}-replicas
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    cluster-name: patroni-{{ app_name }}
    role: replica

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ app_name }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - patch
  - update
  - create
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ app_name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ app_name }}
subjects:
- kind: ServiceAccount
  name: {{ app_name }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patroni-k8s-ep-access
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  resourceNames:
  - kubernetes
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patroni-k8s-ep-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: patroni-k8s-ep-access
subjects:
- kind: ServiceAccount
  name: {{ app_name }}
  namespace: {{ namespace }}