# Temporary hardened version of https://github.com/canonical/documentation-workflows/blob/main/.github/workflows/documentation-checks.yaml
# Replace with https://github.com/canonical/documentation-workflows/issues/44#issuecomment-4170829133 once it is available

name: Check docs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  check-docs:
    name: Check docs
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: docs
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          # Required by sphinx-last-updated-by-git in shallow GitHub Actions checkouts:
          # https://github.com/mgeier/sphinx-last-updated-by-git/blob/a34a9b4eb9e3a57a15b1ff47d9412c01cc573c7f/README.rst?plain=1#L61-L95
          fetch-depth: 0
      - run: make install
      - name: Spell check
        run: make spelling
      - name: Inclusive language check
        run: make woke
      #- name: Link check
      #  run: make linkcheck
    permissions:
      contents: read
