# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Promote charm

on:
  workflow_dispatch:
    inputs:
      revisions:
        description: |
          Comma-separated list of git revision tags to promote.
          These must match the tags created by canonical/data-platform-workflows release_charm_edge.yaml

          Single-charm repo example: 'rev123,rev124'
          Monorepo example: 'mysql/rev123,mysql-k8s/rev124'
        required: true
        type: string
      to-risk:
        description: Promote to this Charmhub risk
        required: true
        type: choice
        options:
          - beta
          - candidate
          - stable

jobs:
  promote:
    name: Promote charm
    uses: canonical/data-platform-workflows/.github/workflows/_promote_charms.yaml@v49.0.1
    with:
      track: '14'
      revisions: ${{ inputs.revisions }}
      to-risk: ${{ inputs.to-risk }}
    secrets:
      charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
    permissions:
      actions: read  # Needed for GitHub API call to get workflow version
      contents: write  # Needed to edit GitHub releases
