# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to Charmhub

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'tests/**'
      - 'docs/**'
      - .github/renovate.json5
      - pyproject.toml
      - '.github/workflows/ci.yaml'
      - '.github/workflows/lib-check.yaml'
      - '.github/workflows/sync_docs.yaml'

jobs:
  ci-tests:
    name: Tests
    uses: ./.github/workflows/ci.yaml
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      GCP_ACCESS_KEY: ${{ secrets.GCP_ACCESS_KEY }}
      GCP_SECRET_KEY: ${{ secrets.GCP_SECRET_KEY }}
    permissions:
      actions: read  # Needed for GitHub API call to get workflow version
      contents: write  # Needed for Allure Report

  release-libraries:
    name: Release libraries
    needs:
      - ci-tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment:
      name: edge
      # Re-use edge token without creating new deployment (release_charm_edge.yaml job will create deployment)
      deployment: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Release charm libraries
        uses: canonical/charming-actions/release-libraries@2.7.0
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
    permissions: {}

  release:
    name: Release charm
    needs:
      - ci-tests
    uses: canonical/data-platform-workflows/.github/workflows/release_charm_edge.yaml@v48.0.3
    with:
      track: 14
      artifact-prefix: ${{ needs.ci-tests.outputs.artifact-prefix }}
    secrets:
      charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
    permissions:
      actions: read  # Needed for GitHub API call to get workflow version
      contents: write  # Needed to create git tags
